workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:4013aa6c297808defd01234fce4a42e1ca0518a5bd0260752a86a46542b38206
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-lock-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/_cacache

  node-v6:
    <<: *node-base
    docker:
      - image: node:6@sha256:684e55c121984775f72f48a2dee8ccaa669d18605f1e77f7da003fc187bceb25
  node-v8:
    <<: *node-base
    docker:
      - image: node:8@sha256:9ad3309f2ab60bb09774cc774ed305bfcda71dca65730ba49073b7269de1cac6
  node-v10:
    <<: *node-base
    docker:
      - image: node:10@sha256:4013aa6c297808defd01234fce4a42e1ca0518a5bd0260752a86a46542b38206
